# Generated by Django 6.0 on 2026-03-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_history',
            name='feature_used',
            field=models.CharField(choices=[('SUPER_RESOLUTION', 'Super Resolution'), ('BASIC_FILTER', 'Basic Filter'), ('DE_NOISE', 'Denoise'), ('DE_BLUR', 'Deblur'), ('SHADOW_REMOVAL', 'Shadow Removal')], default='BASIC_FILTER', max_length=50),
        ),
    ]
