# Generated by Django 6.0.4 on 2026-04-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_history', '0002_user_history_feature_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_history',
            name='feature_used',
            field=models.CharField(choices=[('SUPER_RESOLUTION', 'Super Resolution'), ('COLORIZATION', 'Colorization'), ('DE_NOISE', 'Denoise'), ('DE_BLUR', 'Deblur')], default='DE_NOISE', max_length=50),
        ),
    ]
