# Generated by Django 6.0.4 on 2026-04-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_feature',
            name='name',
            field=models.CharField(choices=[('SUPER_RESOLUTION', 'Super Resolution'), ('COLORIZATION', 'Colorization'), ('DE_NOISE', 'Denoise'), ('DE_BLUR', 'Deblur')], max_length=100),
        ),
    ]
