# Generated by Django 6.0.4 on 2026-04-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ai_processing', '0002_alter_ai_feature_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_feature',
            name='name',
            field=models.CharField(choices=[('SUPER_RESOLUTION', 'Super Resolution'), ('COLORIZATION', 'Colorization'), ('DE_NOISE', 'Denoise'), ('DE_BLUR', 'Deblur'), ('BILATERAL_FILTER', 'Bilateral Filter'), ('GAUSSIAN_FILTER', 'Gaussian Filter'), ('GUIDED_FILTER', 'Guided Filter'), ('MEDIAN_FILTER', 'Median Filter')], max_length=100),
        ),
    ]
